### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by breadcat** [chruth/alpine-cgit#2]
I've been running this container for a while, however since I've updated it to the latest version I've not been able to start the container.

I usually spin up an entire stack using `docker-compose`, here's the relevant section:
```
  cgit:
    image: chruth/alpine-cgit
    container_name: cgit
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $SYNCDIR/src:/git
      - $CONFDIR/cgit/cgitrc:/config/cgitrc
      - $CONFDIR/cgit/cgit.css:/app/cgit.css
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:git.$DOMAIN"
      traefik.port: "80"
```

The error also happens when I try to start the container manually with `docker start cgit`, the error I'm getting is:
```
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/init": stat /init: no such file or directory: unknown
Error: failed to start containers: cgit
```

If you need any further details, let me know.
